language: java
sudo: false
dist: trusty

# build all branches
branches:
  only:
  - gh-pages
  - /.*/

env:
  - _JAVA_OPTIONS='-Xmx500m'

matrix:
  include:
    - jdk: oraclejdk8 # JDK 1.8.0_131-b11 or newer
    - jdk: oraclejdk9 # JDK 9+175 or newer

install:
# Display Gradle, Groovy, JVM and other versions
  - ./gradlew -version

script:
- ./gradlew build --scan --stacktrace